---
- name: Setup vpn services and utilities on a new server
  hosts: all
  become: true
  vars:
    ansible_user: vpn

  roles:
    - role: openvpn
    - role: ssh_hardening
    - role: pihole
    - role: fail2ban
    # - role: x3-ui
