---
- name: Setup vpn services and utilities on a new server
  hosts: all
  become: true
  vars:
    ansible_user: vpn

  roles:
    - role: openvpn
    - role: pihole
    - role: fail2ban
    - role: ssh-hardening
    - role: iptables-hardening
