---
- name: Disable root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
  notify: Restart SSH

- name: Disable password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
  notify: Restart SSH

- name: Disable challenge-response authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?ChallengeResponseAuthentication'
    line: "ChallengeResponseAuthentication no"
    state: present
  notify: Restart SSH

- name: Disable PAM authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?UsePAM'
    line: "UsePAM no"
    state: present
  notify: Restart SSH

- name: Allow only public key authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?AuthenticationMethods'
    line: "AuthenticationMethods publickey"
    state: present
  notify: Restart SSH
